<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            // Large Featured Projects
            [
                'title' => 'E-Commerce Platform with AI Recommendations',
                'slug' => 'ecommerce-platform-ai',
                'description' => 'A comprehensive e-commerce solution featuring AI-powered product recommendations, real-time inventory management, multi-vendor support, and integrated payment gateway. Built with microservices architecture for scalability.',
                'category' => 'Web Application',
                'tech_stack' => ['Laravel', 'Vue.js', 'TailwindCSS', 'PostgreSQL', 'Redis', 'Stripe', 'AWS'],
                'repository_url' => 'https://github.com/example/ecommerce-ai',
                'live_url' => 'https://demo-ecommerce-ai.com',
                'view_count' => 1247,
                'is_featured' => true,
                'size' => 'large',
                'display_order' => 1,
            ],
            [
                'title' => 'Healthcare Management System',
                'slug' => 'healthcare-management-system',
                'description' => 'Complete hospital management system with patient records, appointment scheduling, billing, pharmacy management, and telemedicine capabilities. HIPAA compliant with end-to-end encryption.',
                'category' => 'Enterprise',
                'tech_stack' => ['Laravel', 'React', 'MySQL', 'Socket.io', 'Docker', 'Kubernetes'],
                'repository_url' => null,
                'live_url' => null,
                'view_count' => 892,
                'is_featured' => true,
                'size' => 'large',
                'display_order' => 2,
            ],
            [
                'title' => 'Real Estate Marketplace',
                'slug' => 'real-estate-marketplace',
                'description' => 'Modern property listing platform with advanced search filters, virtual tours, mortgage calculator, agent dashboard, and integrated CRM. Features map-based property discovery and AI-powered price estimation.',
                'category' => 'Marketplace',
                'tech_stack' => ['Laravel', 'Next.js', 'TypeScript', 'PostgreSQL', 'Mapbox', 'Cloudinary'],
                'repository_url' => 'https://github.com/example/real-estate',
                'live_url' => 'https://demo-realestate.com',
                'view_count' => 2103,
                'is_featured' => true,
                'size' => 'large',
                'display_order' => 3,
            ],

            // Medium Projects
            [
                'title' => 'Project Management Tool',
                'slug' => 'project-management-tool',
                'description' => 'Collaborative project management platform with Kanban boards, Gantt charts, time tracking, team collaboration, and reporting. Supports agile and waterfall methodologies.',
                'category' => 'Productivity',
                'tech_stack' => ['Laravel', 'Livewire', 'Alpine.js', 'MySQL', 'Chart.js'],
                'repository_url' => 'https://github.com/example/pm-tool',
                'live_url' => 'https://demo-pm.com',
                'view_count' => 1456,
                'is_featured' => true,
                'size' => 'medium',
                'display_order' => 4,
            ],
            [
                'title' => 'Learning Management System',
                'slug' => 'learning-management-system',
                'description' => 'Online education platform with course creation, video hosting, quizzes, certificates, student progress tracking, and payment integration. Supports live classes and discussion forums.',
                'category' => 'Education',
                'tech_stack' => ['Laravel', 'Vue.js', 'Vimeo API', 'Stripe', 'WebRTC'],
                'repository_url' => 'https://github.com/example/lms',
                'live_url' => null,
                'view_count' => 634,
                'is_featured' => true,
                'size' => 'medium',
                'display_order' => 5,
            ],
            [
                'title' => 'Restaurant Booking & POS System',
                'slug' => 'restaurant-booking-pos',
                'description' => 'Complete restaurant solution with online reservations, table management, POS system, kitchen display, inventory tracking, and customer loyalty program.',
                'category' => 'Business',
                'tech_stack' => ['Laravel', 'React', 'MySQL', 'Pusher', 'Twilio'],
                'repository_url' => null,
                'live_url' => 'https://demo-restaurant.com',
                'view_count' => 478,
                'is_featured' => false,
                'size' => 'medium',
                'display_order' => 6,
            ],
            [
                'title' => 'Social Media Analytics Dashboard',
                'slug' => 'social-media-analytics',
                'description' => 'Multi-platform social media analytics tool with engagement tracking, sentiment analysis, competitor monitoring, and automated reporting for Instagram, Twitter, and Facebook.',
                'category' => 'Analytics',
                'tech_stack' => ['Laravel', 'React', 'Chart.js', 'Redis', 'Social APIs'],
                'repository_url' => 'https://github.com/example/social-analytics',
                'live_url' => null,
                'view_count' => 823,
                'is_featured' => false,
                'size' => 'medium',
                'display_order' => 7,
            ],
            [
                'title' => 'Inventory Management System',
                'slug' => 'inventory-management-system',
                'description' => 'Warehouse and inventory management with barcode scanning, stock alerts, purchase orders, supplier management, and multi-location support.',
                'category' => 'Business',
                'tech_stack' => ['Laravel', 'Vue.js', 'MySQL', 'Barcode.js'],
                'repository_url' => 'https://github.com/example/inventory',
                'live_url' => null,
                'view_count' => 567,
                'is_featured' => false,
                'size' => 'medium',
                'display_order' => 8,
            ],

            // Small Projects
            [
                'title' => 'Personal Finance Tracker',
                'slug' => 'personal-finance-tracker',
                'description' => 'Budget management app with expense tracking, income monitoring, financial goals, and visual reports. Supports multiple currencies and bank account integration.',
                'category' => 'Finance',
                'tech_stack' => ['Laravel', 'Alpine.js', 'Chart.js', 'SQLite'],
                'repository_url' => 'https://github.com/example/finance-tracker',
                'live_url' => 'https://demo-finance.com',
                'view_count' => 345,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 9,
            ],
            [
                'title' => 'Weather Dashboard',
                'slug' => 'weather-dashboard',
                'description' => 'Real-time weather information with 7-day forecasts, weather maps, severe weather alerts, and location-based recommendations.',
                'category' => 'Utility',
                'tech_stack' => ['Vue.js', 'OpenWeather API', 'Mapbox', 'Chart.js'],
                'repository_url' => 'https://github.com/example/weather',
                'live_url' => 'https://demo-weather.com',
                'view_count' => 234,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 10,
            ],
            [
                'title' => 'URL Shortener Service',
                'slug' => 'url-shortener-service',
                'description' => 'Custom URL shortening service with analytics, QR code generation, link expiration, and password protection.',
                'category' => 'Utility',
                'tech_stack' => ['Laravel', 'Redis', 'Chart.js'],
                'repository_url' => 'https://github.com/example/url-shortener',
                'live_url' => 'https://short.ly',
                'view_count' => 456,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 11,
            ],
            [
                'title' => 'Task Timer & Productivity App',
                'slug' => 'task-timer-productivity',
                'description' => 'Pomodoro timer with task management, productivity statistics, and focus mode. Helps track time spent on different projects.',
                'category' => 'Productivity',
                'tech_stack' => ['Vue.js', 'LocalStorage', 'PWA'],
                'repository_url' => 'https://github.com/example/task-timer',
                'live_url' => 'https://demo-timer.com',
                'view_count' => 189,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 12,
            ],
            [
                'title' => 'Recipe Collection App',
                'slug' => 'recipe-collection-app',
                'description' => 'Personal recipe manager with ingredient lists, cooking instructions, meal planning, and shopping list generation.',
                'category' => 'Lifestyle',
                'tech_stack' => ['Laravel', 'Blade', 'MySQL'],
                'repository_url' => 'https://github.com/example/recipes',
                'live_url' => null,
                'view_count' => 278,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 13,
            ],
            [
                'title' => 'Portfolio CMS',
                'slug' => 'portfolio-cms',
                'description' => 'Content management system specifically designed for creative professionals to showcase their work with customizable themes.',
                'category' => 'CMS',
                'tech_stack' => ['Laravel', 'Blade', 'TailwindCSS', 'SQLite'],
                'repository_url' => 'https://github.com/example/portfolio-cms',
                'live_url' => null,
                'view_count' => 512,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 14,
            ],
            [
                'title' => 'Markdown Blog Engine',
                'slug' => 'markdown-blog-engine',
                'description' => 'Lightweight blog platform using markdown files with syntax highlighting, tags, categories, and RSS feed.',
                'category' => 'Blog',
                'tech_stack' => ['Laravel', 'Markdown', 'Prism.js'],
                'repository_url' => 'https://github.com/example/md-blog',
                'live_url' => 'https://demo-blog.com',
                'view_count' => 423,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 15,
            ],
            [
                'title' => 'Event Countdown Timer',
                'slug' => 'event-countdown-timer',
                'description' => 'Create and share countdown timers for important events with customizable themes and social sharing.',
                'category' => 'Utility',
                'tech_stack' => ['Vue.js', 'TailwindCSS'],
                'repository_url' => 'https://github.com/example/countdown',
                'live_url' => 'https://countdown.app',
                'view_count' => 167,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 16,
            ],
            [
                'title' => 'QR Code Generator',
                'slug' => 'qr-code-generator',
                'description' => 'Generate customizable QR codes for URLs, text, contact cards, and WiFi credentials with download options.',
                'category' => 'Utility',
                'tech_stack' => ['Laravel', 'QR Code Library', 'Alpine.js'],
                'repository_url' => 'https://github.com/example/qr-generator',
                'live_url' => 'https://qr-gen.app',
                'view_count' => 298,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 17,
            ],
            [
                'title' => 'Password Generator Tool',
                'slug' => 'password-generator-tool',
                'description' => 'Secure password generator with customizable length, character types, and strength indicator.',
                'category' => 'Security',
                'tech_stack' => ['JavaScript', 'TailwindCSS'],
                'repository_url' => 'https://github.com/example/password-gen',
                'live_url' => 'https://passgen.app',
                'view_count' => 445,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 18,
            ],
            [
                'title' => 'Color Palette Generator',
                'slug' => 'color-palette-generator',
                'description' => 'Generate beautiful color palettes for design projects with export options for various formats.',
                'category' => 'Design',
                'tech_stack' => ['Vue.js', 'Color.js', 'TailwindCSS'],
                'repository_url' => 'https://github.com/example/color-palette',
                'live_url' => 'https://colors.app',
                'view_count' => 678,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 19,
            ],
            [
                'title' => 'Habit Tracker',
                'slug' => 'habit-tracker',
                'description' => 'Daily habit tracking app with streak counting, statistics, and motivational quotes.',
                'category' => 'Productivity',
                'tech_stack' => ['Laravel', 'Alpine.js', 'Chart.js'],
                'repository_url' => 'https://github.com/example/habit-tracker',
                'live_url' => null,
                'view_count' => 356,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 20,
            ],
            [
                'title' => 'Expense Splitter',
                'slug' => 'expense-splitter',
                'description' => 'Split bills and expenses among friends with automatic calculation and settlement tracking.',
                'category' => 'Finance',
                'tech_stack' => ['Laravel', 'Vue.js', 'MySQL'],
                'repository_url' => 'https://github.com/example/expense-splitter',
                'live_url' => 'https://split-it.app',
                'view_count' => 289,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 21,
            ],
            [
                'title' => 'Fitness Workout Logger',
                'slug' => 'fitness-workout-logger',
                'description' => 'Track workouts, exercises, sets, reps, and progress over time with visual charts.',
                'category' => 'Health',
                'tech_stack' => ['Laravel', 'Chart.js', 'MySQL'],
                'repository_url' => 'https://github.com/example/workout-logger',
                'live_url' => null,
                'view_count' => 412,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 22,
            ],
            [
                'title' => 'Reading List Manager',
                'slug' => 'reading-list-manager',
                'description' => 'Organize books to read with ratings, reviews, reading progress, and recommendations.',
                'category' => 'Lifestyle',
                'tech_stack' => ['Laravel', 'Blade', 'MySQL'],
                'repository_url' => 'https://github.com/example/reading-list',
                'live_url' => null,
                'view_count' => 234,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 23,
            ],
            [
                'title' => 'Note Taking App',
                'slug' => 'note-taking-app',
                'description' => 'Simple and elegant note-taking application with markdown support, tags, and search.',
                'category' => 'Productivity',
                'tech_stack' => ['Laravel', 'Vue.js', 'Markdown', 'MySQL'],
                'repository_url' => 'https://github.com/example/notes',
                'live_url' => 'https://notes.app',
                'view_count' => 567,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 24,
            ],
            [
                'title' => 'Contact Form Builder',
                'slug' => 'contact-form-builder',
                'description' => 'Drag-and-drop contact form builder with email notifications and spam protection.',
                'category' => 'Utility',
                'tech_stack' => ['Laravel', 'Vue.js', 'reCAPTCHA'],
                'repository_url' => 'https://github.com/example/form-builder',
                'live_url' => null,
                'view_count' => 198,
                'is_featured' => false,
                'size' => 'small',
                'display_order' => 25,
            ],
        ];

        foreach ($projects as $project) {
            Project::create($project);
        }
    }
}
