<?php

namespace Database\Seeders;

use App\Models\Testimonial;
use Illuminate\Database\Seeder;

class TestimonialSeeder extends Seeder
{
    public function run(): void
    {
        $testimonials = [
            [
                'client_name' => 'Sarah Johnson',
                'client_position' => 'CEO',
                'client_company' => 'TechStart Inc',
                'content' => 'Working with this developer was an absolute pleasure. The project was delivered on time and exceeded our expectations. The attention to detail and commitment to quality is outstanding. Highly recommended for any serious web development project!',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 1,
            ],
            [
                'client_name' => 'Michael Chen',
                'client_position' => 'Product Manager',
                'client_company' => 'InnovateCo',
                'content' => 'Exceptional work quality and great communication throughout the project. The final product was exactly what we needed, and the developer went above and beyond to ensure everything was perfect. Would definitely work together again!',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 2,
            ],
            [
                'client_name' => 'Emily Rodriguez',
                'client_position' => 'Marketing Director',
                'client_company' => 'GrowthLabs',
                'content' => 'Very professional and skilled developer. Delivered a beautiful and functional website that our clients love. The design is modern and the performance is excellent. Great experience from start to finish.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 3,
            ],
            [
                'client_name' => 'David Kim',
                'client_position' => 'Founder',
                'client_company' => 'StartupHub',
                'content' => 'Great attention to detail and excellent problem-solving skills. The developer understood our vision and brought it to life with precision. Very satisfied with the results and the collaborative process.',
                'rating' => 4,
                'is_approved' => true,
                'display_order' => 4,
            ],
            [
                'client_name' => 'Lisa Anderson',
                'client_position' => 'CTO',
                'client_company' => 'DataFlow Systems',
                'content' => 'Impressive technical skills and ability to understand complex requirements. The project was a success and our team is very happy with the outcome. The code quality is top-notch and well-documented.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 5,
            ],
            [
                'client_name' => 'James Wilson',
                'client_position' => 'Operations Manager',
                'client_company' => 'LogiTech Solutions',
                'content' => 'The developer delivered our inventory management system ahead of schedule. The system is intuitive, fast, and has significantly improved our workflow. Excellent communication and technical expertise.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 6,
            ],
            [
                'client_name' => 'Maria Garcia',
                'client_position' => 'Creative Director',
                'client_company' => 'Design Studio Pro',
                'content' => 'Beautiful UI/UX work! The developer has a great eye for design and understands user experience principles. Our clients have been giving us amazing feedback about the new website.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 7,
            ],
            [
                'client_name' => 'Robert Taylor',
                'client_position' => 'Business Owner',
                'client_company' => 'Taylor\'s Restaurant Group',
                'content' => 'The booking system has transformed how we manage reservations. It\'s user-friendly for both our staff and customers. Great value for money and ongoing support has been excellent.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 8,
            ],
            [
                'client_name' => 'Jennifer Lee',
                'client_position' => 'HR Director',
                'client_company' => 'PeopleFirst Corp',
                'content' => 'Developed a custom HR management system that perfectly fits our needs. The developer took time to understand our processes and delivered a solution that has made our work much more efficient.',
                'rating' => 4,
                'is_approved' => true,
                'display_order' => 9,
            ],
            [
                'client_name' => 'Thomas Brown',
                'client_position' => 'E-commerce Manager',
                'client_company' => 'ShopSmart Online',
                'content' => 'Our online store has never looked better or performed faster. The developer implemented all the features we requested and suggested improvements we hadn\'t even thought of. Sales have increased by 40% since launch!',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 10,
            ],
            [
                'client_name' => 'Amanda White',
                'client_position' => 'Education Coordinator',
                'client_company' => 'LearnOnline Academy',
                'content' => 'The learning management system is exactly what we needed for our online courses. Students find it easy to use and instructors love the admin panel. Highly recommend for educational projects.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 11,
            ],
            [
                'client_name' => 'Christopher Martinez',
                'client_position' => 'Real Estate Broker',
                'client_company' => 'Prime Properties',
                'content' => 'The property listing platform has revolutionized how we showcase homes to clients. The virtual tour feature is a game-changer. Professional work and great support throughout the project.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 12,
            ],
            [
                'client_name' => 'Patricia Davis',
                'client_position' => 'Clinic Administrator',
                'client_company' => 'HealthCare Plus',
                'content' => 'The patient management system has streamlined our operations significantly. Appointment scheduling is now effortless and patient records are well-organized. Very satisfied with the results.',
                'rating' => 4,
                'is_approved' => true,
                'display_order' => 13,
            ],
            [
                'client_name' => 'Daniel Thompson',
                'client_position' => 'Project Lead',
                'client_company' => 'BuildRight Construction',
                'content' => 'Excellent project management tool that keeps our team organized and on track. The reporting features are particularly useful for client updates. Great collaboration with the developer.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 14,
            ],
            [
                'client_name' => 'Michelle Adams',
                'client_position' => 'Fitness Studio Owner',
                'client_company' => 'FitLife Studios',
                'content' => 'The booking and membership management system is perfect for our fitness studio. Members can easily book classes and track their progress. The developer was very responsive to our feedback.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 15,
            ],
            [
                'client_name' => 'Kevin O\'Brien',
                'client_position' => 'Financial Advisor',
                'client_company' => 'WealthWise Consulting',
                'content' => 'The financial planning tool developed for our clients is intuitive and powerful. It has helped us provide better service and our clients appreciate the transparency. Well done!',
                'rating' => 4,
                'is_approved' => true,
                'display_order' => 16,
            ],
            [
                'client_name' => 'Rachel Green',
                'client_position' => 'Event Coordinator',
                'client_company' => 'EventPro Management',
                'content' => 'Our event management platform is now the backbone of our business. From ticketing to attendee management, everything works seamlessly. The developer understood our industry needs perfectly.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 17,
            ],
            [
                'client_name' => 'Brian Clark',
                'client_position' => 'Supply Chain Manager',
                'client_company' => 'GlobalTrade Inc',
                'content' => 'The logistics tracking system has given us real-time visibility into our supply chain. The integration with our existing systems was smooth. Professional and reliable developer.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 18,
            ],
            [
                'client_name' => 'Nicole Turner',
                'client_position' => 'Content Manager',
                'client_company' => 'MediaHub Digital',
                'content' => 'The CMS is user-friendly and powerful. Our content team can now publish and manage content without technical assistance. The developer provided excellent training and documentation.',
                'rating' => 4,
                'is_approved' => true,
                'display_order' => 19,
            ],
            [
                'client_name' => 'Steven Harris',
                'client_position' => 'Restaurant Owner',
                'client_company' => 'Gourmet Kitchen',
                'content' => 'The POS system has made our restaurant operations so much smoother. Order management, kitchen display, and reporting all work flawlessly. Great investment for our business.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 20,
            ],
            [
                'client_name' => 'Laura Phillips',
                'client_position' => 'Nonprofit Director',
                'client_company' => 'Community Outreach Foundation',
                'content' => 'The donor management and fundraising platform has helped us increase donations and better engage with our supporters. The developer was generous with their time and expertise.',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 21,
            ],
            [
                'client_name' => 'Andrew Scott',
                'client_position' => 'Tech Startup Founder',
                'client_company' => 'InnovateTech Labs',
                'content' => 'The MVP was delivered quickly without compromising on quality. The developer helped us validate our idea and get to market fast. Looking forward to working together on the next phase!',
                'rating' => 5,
                'is_approved' => true,
                'display_order' => 22,
            ],
        ];

        foreach ($testimonials as $testimonial) {
            Testimonial::create($testimonial);
        }
    }
}
